name: CI/CD Backend -> Docker Hub -> EC2

on:
  push:
    branches: [deploy]
  workflow_dispatch:

jobs:
  build-push-deploy:
    runs-on: [self-hosted, back]
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Login en Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build imagen backend
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/back-eval2:latest \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/back-eval2:${{ github.sha }} \
            .

      - name: Push a Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/back-eval2:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/back-eval2:${{ github.sha }}

      - name: Deploy local (runner == EC2-back)
        run: |
          mkdir -p ~/app/initdb
          cp docker-compose.yml ~/app/docker-compose.yml
          cp initdb/*.sql ~/app/initdb/
          cd ~/app
          docker compose pull backend
          docker compose up -d
          docker image prune -f
          docker ps
